version: '3.8'

services:
  # service Php
  php:
    build: './php_docker/'
    container_name: php_biblio
    volumes:
      - ./www/:/var/www/html
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}

  # service Apache
  apache:
    build: './apache_docker/'
    container_name: apache_biblio
    depends_on:
      - php
    ports:
      - '8081:80'
    volumes:
      - ./www/:/var/www/html

  # service DB
  mariadb:
    image: mariadb:11.2
    restart: unless-stopped
    container_name: biblio_db
    ports:
      - '3312:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
    volumes:
      - bibliodatabase:/var/lib/mysql

  # service phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_biblio
    ports:
      - '8082:80'
    environment:
      - PMA_HOST=biblio_db
    depends_on:
      - mariadb

volumes:
  bibliodatabase:
